[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = [

    # UNIVERSAL:

    "F",  # Pyflakes
    "W",  # pycodestyle warning
    "E",  # pycodestyle error
    "C90",  # mccabe
    "I",  # isort
    "N",  # pep8-naming
    "D",  # pydocstyle
    "UP",  # pyupgrade
    "BLE",  # flake8-blind-except
    "FBT",  # flake8-boolean-trap
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "C4",  # flake8-comprehensions
    "EM",  # flake8-errmsg
    "EXE",  # flake8-executable
    "FA",  # flake8-future-annotations
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "LOG",  # flake8-logging
    "G",  # flake8-logging-format
    "INP",  # flake8-no-pep420
    "PIE",  # flake8-pie
    "PYI",  # flake8-pyi
    "Q",  # flake8-quotes
    "RSE",  # flake8-raise
    "RET",  # flake8-return
    "SLF",  # flake8-self
    "SLOT",  # flake8-slots
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "TCH",  # flake8-type-checking
    "INT",  # flake8-gettext
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "PGH",  # pygrep-hooks
    "PL",  # Pylint
    "TRY",  # tryceratops
    "FLY",  # flynt
    "PERF",  # Perflint
    "FURB",  # refurb
    "RUF",  # Ruff-specific rules

    # OPTIONAL:

    "YTT",  # flake8-2020
    "ANN",  # flake8-annotations
    "ASYNC",  # flake8-async
    "S",  # flake8-bandit
    "DTZ",  # flake8-datetimez
    "NPY",  # NumPy-specific rules
    "PD",  # pandas-vet
    "PT",  # flake8-pytest-style

    # IGNORE:

    "COM", # flake8-commas
    "CPY",  # flake8-copyright
    "T10",  # flake8-debugger
    "DJ",  # flake8-django
    "T20",  # flake8-print
    "TD",  # flake8-todos
    "FIX",  # flake8-fixme
    "ERA",  # eradicate
    "AIR",  # Airflow
]

ignore = [
    "D10",
    "PT004",  # https://github.com/astral-sh/ruff/issues/8796
    "PT005",  # https://github.com/astral-sh/ruff/issues/8796
    "PT007",
    "S101",
    "UP040",  # mypy does not support yet
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ARG001", "ARG004", "FBT001"]  # not compatible with pytest logic

[tool.ruff.lint.isort]
force-single-line = false
order-by-type = false
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.pydocstyle]
# https://github.com/astral-sh/ruff/issues/6606
# convention = "sphinx"
convention = "google"

[tool.mypy]
exclude = ".venv"
python_version = "3.12"

check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
extra_checks = true
follow_imports = "normal"
ignore_missing_imports = false
local_partial_types = true
no_implicit_optional = true
no_implicit_reexport = true
show_error_codes = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
# allure is not type annotated
module = ["allure", "docker"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
# PyHamcrest has a lot of incorrect type annotations
module = ["hamcrest"]
follow_imports = "skip"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = "^1.11.1"
ruff = "^0.6.0"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
