line-length = 120
target-version = "py314"

[lint]
select = ["ALL"]

ignore = [
    "COM",     # flake8-commas
    "CPY",     # flake8-copyright
    "T20",     # flake8-print
    "FIX",     # flake8-fixme
    "ERA",     # eradicate

    "any-type",
    "D10",     # Undocumented
    "pytest-parametrize-values-wrong-type",
    "pytest-fixture-param-without-value",
    "parenthesize-chained-operators",
    "assert",
    "missing-todo-author",
    "suspicious-subprocess-import",
]

[lint.per-file-ignores]
"tests/*" = [
    "unused-function-argument",
    "unused-method-argument",
    "unused-static-method-argument",
    "boolean-type-hint-positional-argument",
    "private-member-access",
    "too-many-arguments",
    "too-many-locals",
]
"tests/integration/*" = [
    "too-many-positional-arguments",
]
"tests/unit/*" = [
    "import-outside-top-level",
    "too-many-positional-arguments",
    "import-private-name",
]
"**/tests/fixtures/unit.py" = [
    "import-outside-top-level",
    "import-private-name",
]

[lint.isort]
force-single-line = false
order-by-type = false

[lint.pydocstyle]
# https://github.com/astral-sh/ruff/issues/6606
# convention = "sphinx"
convention = "google"
